name: main

on:
  pull_request:
  push:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  mac_win_test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]
        os: [ windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox virtualenv setuptools
      - name: tox test
        run: |
          tox -e py
  lin_lint:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox virtualenv setuptools
      - name: tox lint
        run: |
          tox -e py
          if [ ${{ matrix.python-version }} = "3.10" ]; then tox -e pre-commit,mypy,flake8; fi
